class Selection
  include Mongoid::Document
  field :baseball_team, type: String
  field :football_team, type: String
  field :basketball_team, type: String
  field :hockey_team, type: String

  belongs_to :user

  def self.baseball_options
  	[["Arizona Diamondbacks","Arizona Diamondbacks"],
  	["Atlanta Braves","Atlanta Braves"],
	["Baltimore Orioles","Baltimore Orioles"],
	["Boston Red Sox","Boston Red Sox"],
	["Chicago Cubs","Chicago Cubs"],
	["Chicago White Sox","Chicago White Sox"],
	["Cincinnati Reds","Cincinnati Reds"],
	["Cleveland Indians","Cleveland Indians"],
	["Colorado Rockies","Colorado Rockies"],
	["Detroit Tigers","Detroit Tigers"],
	["Houston Astros","Houston Astros"],
	["Kansas City Royals","Kansas City Royals"],
	["Los Angeles Angels of Anaheim","Los Angeles Angels of Anaheim"],
	["Los Angeles Dodgers","Los Angeles Dodgers"],
	["Miami Marlins","Miami Marlins"],
	["Milwaukee Brewers","Milwaukee Brewers"],
	["Minnesota Twins","Minnesota Twins"],
	["New York Mets","New York Mets"],
	["New York Yankees","New York Yankees"],
	["Oakland Athletics","Oakland Athletics"],
	["Philadelphia Phillies","Philadelphia Phillies"],
	["Pittsburgh Pirates","Pittsburgh Pirates"],
	["San Diego Padres","San Diego Padres"],
	["San Francisco Giants","San Francisco Giants"],
	["Seattle Mariners","Seattle Mariners"],
	["St. Louis Cardinals","St. Louis Cardinals"],
	["Tampa Bay Rays","Tampa Bay Rays"],
	["Texas Rangers","Texas Rangers"],
	["Toronto Blue Jays","Toronto Blue Jays"],
	["Washington Nationals","Washington Nationals"],]
  end

  def self.football_options
  	[["Chicago Bears","Chicago Bears"],
	["Arizona Cardinals","Arizona Cardinals"],
	["Green Bay Packers","Green Bay Packers"],
	["New York Giants","New York Giants"],
	["Detroit Lions","Detroit Lions"],
	["Washington Redskins","Washington Redskins"],
	["Pittsburgh Steelers","Pittsburgh Steelers"],
	["Philadelphia Eagles","Philadelphia Eagles"],
	["St. Louis Rams","St. Louis Rams"],
	["San Francisco 49ers","San Francisco 49ers"],
	["Cleveland Browns","Cleveland Browns"],
	["Indianapolis Colts","Indianapolis Colts"],
	["Dallas Cowboys","Dallas Cowboys"],
	["Oakland Raiders","Oakland Raiders"],
	["New England Patriots","New England Patriots"],
	["Tennessee Titans","Tennessee Titans"],
	["Denver Broncos","Denver Broncos"],
	["San Diego Chargers","San Diego Chargers"],
	["New York Jets","New York Jets"],
	["Kansas City Chiefs","Kansas City Chiefs"],
	["Buffalo Bills","Buffalo Bills"],
	["Minnesota Vikings","Minnesota Vikings"],
	["Miami Dolphins","Miami Dolphins"],
	["Atlanta Falcons","Atlanta Falcons"],
	["New Orleans Saints","New Orleans Saints"],
	["Cincinnati Bengals","Cincinnati Bengals"],
	["Seattle Seahawks","Seattle Seahawks"],
	["Tampa Bay Buccaneers","Tampa Bay Buccaneers"],
	["Jacksonville Jaguars","Jacksonville Jaguars"],
	["Carolina Panthers","Carolina Panthers"],
	["Baltimore Ravens","Baltimore Ravens"],
	["Houston Texans","Houston Texans"]]
  end

  def self.hockey_options
	[["Anaheim Ducks","Anaheim Ducks"],
	["Boston Bruins","Boston Bruins"],
	["Buffalo Sabres","Buffalo Sabres"],
	["Calgary Flames","Calgary Flames"],
	["Carolina Hurricanes","Carolina Hurricanes"],
	["Chicago Blackhawks","Chicago Blackhawks"],
	["Colorado Avalanche","Colorado Avalanche"],
	["Columbus Blue Jackets","Columbus Blue Jackets"],
	["Dallas Stars","Dallas Stars"],
	["Detroit Red Wings","Detroit Red Wings"],
	["Edmonton Oilers","Edmonton Oilers"],
	["Florida Panthers","Florida Panthers"],
	["Los Angeles Kings","Los Angeles Kings"],
	["Minnesota Wild","Minnesota Wild"],
	["Montreal Canadiens","Montreal Canadiens"],
	["Nashville Predators","Nashville Predators"],
	["New Jersey Devils","New Jersey Devils"],
	["New York Islanders","New York Islanders"],
	["New York Rangers","New York Rangers"],
	["Philadelphia Flyers","Philadelphia Flyers"],
	["Phoenix Coyotes","Phoenix Coyotes"],
	["Pittsburgh Penguins","Pittsburgh Penguins"],
	["Ottawa Senators","Ottawa Senators"],
	["San Jose Sharks","San Jose Sharks"],
	["St Louis Blues","St Louis Blues"],
	["Tampa Bay Lightning","Tampa Bay Lightning"],
	["Toronto Maple Leafs","Toronto Maple Leafs"],
	["Vancouver Canucks","Vancouver Canucks"],
	["Washington Capitals","Washington Capitals"],
	["Winnipeg Jets","Winnipeg Jets"]]
  end

  def self.basketball_options
	[["Atlanta Hawks","Atlanta Hawks"],
	["Boston Celtics","Boston Celtics"],
	["Brooklyn Nets","Brooklyn Nets"],
	["Charlotte Bobcats","Charlotte Bobcats"],
	["Chicago Bulls","Chicago Bulls"],
	["Cleveland Cavaliers","Cleveland Cavaliers"],
	["Dallas Mavericks","Dallas Mavericks"],
	["Denver Nuggets","Denver Nuggets"],
	["Detroit Pistons","Detroit Pistons"],
	["Golden State Warriors","Golden State Warriors"],
	["Houston Rockets","Houston Rockets"],
	["Indiana Pacers","Indiana Pacers"],
	["Los Angeles Clippers","Los Angeles Clippers"],
	["Los Angeles Lakers","Los Angeles Lakers"],
	["Memphis Grizzlies","Memphis Grizzlies"],
	["Miami Heat","Miami Heat"],
	["Milwaukee Bucks","Milwaukee Bucks"],
	["Minnesota Timberwolves","Minnesota Timberwolves"],
	["New Orleans Pelicans","New Orleans Pelicans"],
	["New York Knicks","New York Knicks"],
	["Oklahoma City Thunder","Oklahoma City Thunder"],
	["Orlando Magic","Orlando Magic"],
	["Philadelphia 76ers","Philadelphia 76ers"],
	["Phoenix Suns","Phoenix Suns"],
	["Portland Trail Blazers","Portland Trail Blazers"],
	["Sacramento Kings","Sacramento Kings"],
	["San Antonio Spurs","San Antonio Spurs"],
	["Toronto Raptors","Toronto Raptors"],
	["Utah Jazz","Utah Jazz"],
	["Washington Wizards","Washington Wizards"]]
  end

end
